# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-test
  template:
    metadata:
      labels:
        app: storage-test
    spec:
      containers:
      - name: test-container
        image: ubuntu:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y pv
            sleep infinity
        volumeMounts:
        - name: local-storage
          mountPath: /data
      volumes:
      - name: local-storage
        persistentVolumeClaim:
          claimName: local-storage-claim
